apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: crigor/todo
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: todo-database-url
                key: database-url
